Remove files to allow copy when targets are identical
Fixes:

```
cp: LICENSE and /Users/ec2-user/actions-runner/_work/amalthea/amalthea/LICENSE are identical (not copied).
Error: Process completed with exit code 1.
```

But do we even need to copy?