Update ctor from 0.1 to 1.0 (#1192)
Progress towards https://github.com/posit-dev/ark/issues/1162

Fixes:

```
error: Missing unsafe keyword in #[ctor] annotation. Use #[ctor(unsafe)]. This error can be suppressed by passing `--cfg linktime_no_fail_on_missing_unsafe` in `RUSTFLAGS` or placing this in your `config.toml` file.


       #[ctor]
       ^^^^^^^------- replace this with #[ctor(unsafe)]
```

From this change:

```
unsafe` is now required for `#[ctor]` items and the `no_warn_on_missing_unsafe` feature is gone.
>   - `RUSTFLAGS="--cfg linktime_no_fail_on_missing_unsafe"` can bypass the error.
```