Fix evaluate test flakiness
failures:
        dap_evaluate::test_dap_evaluate_infloop_times_out

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 428
filtered out; finished in 16.27s

  stderr ───

    thread 'dap_evaluate::test_dap_evaluate_infloop_times_out' (2016)
panicked at crates\ark\tests\integration\dap_evaluate.rs:455:19:
    Failed to receive DAP message: A connection attempt failed because
the connected party did not properly respond after a period of time, or
established connection failed because connected host has failed to
respond. (os error 10060)